# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_files/account_add_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountAdd(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(389, 305)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.name_select_combo = QtWidgets.QLineEdit(Form)
        self.name_select_combo.setText("")
        self.name_select_combo.setObjectName("name_select_combo")
        self.verticalLayout.addWidget(self.name_select_combo)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.type_select_combo = QtWidgets.QComboBox(Form)
        self.type_select_combo.setEditable(False)
        self.type_select_combo.setObjectName("type_select_combo")
        self.type_select_combo.addItem("")
        self.type_select_combo.addItem("")
        self.type_select_combo.addItem("")
        self.type_select_combo.addItem("")
        self.type_select_combo.addItem("")
        self.verticalLayout.addWidget(self.type_select_combo)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.currency_select_combo = QtWidgets.QComboBox(Form)
        self.currency_select_combo.setEditable(True)
        self.currency_select_combo.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.currency_select_combo.setObjectName("currency_select_combo")
        self.verticalLayout.addWidget(self.currency_select_combo)
        self.submit_button = QtWidgets.QPushButton(Form)
        self.submit_button.setObjectName("submit_button")
        self.verticalLayout.addWidget(self.submit_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "1. Type the name for the account"))
        self.name_select_combo.setPlaceholderText(_translate("Form", "e.g., Lloyds Bank Account"))
        self.label_2.setText(_translate("Form", "2. Set the type of the account"))
        self.type_select_combo.setItemText(0, _translate("Form", "Bank"))
        self.type_select_combo.setItemText(1, _translate("Form", "Cash"))
        self.type_select_combo.setItemText(2, _translate("Form", "Credit Card"))
        self.type_select_combo.setItemText(3, _translate("Form", "Investment"))
        self.type_select_combo.setItemText(4, _translate("Form", "Other"))
        self.label_3.setText(_translate("Form", "3. Set the currency"))
        self.currency_select_combo.setPlaceholderText(_translate("Form", "Search Currency ..."))
        self.submit_button.setText(_translate("Form", "Submit"))
